version: '2'  # if no version is specified then v1 is assumed. Recommend v2 minimum

services:  # containers. same as docker run
  mysite: # a friendly name. this is also DNS name inside network
    image: nginx # Optional if you use build:
    command: # Optional, replace the default CMD specified by the image
    volumes:
      - .:/site
    ports:
      -'80:80'
      -'443:443'
  servicename2:

volumes: # Optional, same as docker volume create

networks: # Optional, same as docker network create



